version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.17.1
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          # host port: 3800  Optional, default value is 3306. The port of host
          # container port: 3306  Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          #mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'go_application' # Optional, default value is "test". The specified database which will be create
          mysql root password: pass # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'crud_user' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: pass # Required if "mysql user" exists. The password for the "mysql user"
      - checkout
      - run:
          name: Run tests and coverage
          command: go test ./repository/ ./utils/ -race -covermode=atomic -coverprofile=coverage.out
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)
      
workflow:
  version: 2.1
  build-test:
    jobs:
      - build
